package cop5556fa18;

import java.util.ArrayList;
import java.util.Arrays;

public class PLPScanner {
	
	@SuppressWarnings("serial")
	public static class LexicalException extends Exception {

		int pos;

		public LexicalException(String message, int pos) {
			super(message);
			this.pos = pos;
		}

		public int getPos() {
			return pos;
		}
	}
	
	public static enum Kind {
		IDENTIFIER, INTEGER_LITERAL, BOOLEAN_LITERAL, FLOAT_LITERAL,
		STRING_LITERAL, CHAR_LITERAL,
		KW_print        /* print       */,
		KW_sleep        /* sleep       */,
		KW_int          /* int         */,
		KW_float        /* float       */,
		KW_boolean      /* boolean     */,
		KW_if           /* if          */,
		KW_while 		/* while 	   */,
		KW_char         /* char        */,
		KW_string       /* string      */,
		KW_abs			/* abs 		   */,
		KW_sin			/* sin 		   */,
		KW_cos			/* cos 		   */, 
		KW_atan			/* atan        */,
		KW_log			/* log 		   */,
		OP_ASSIGN       /* =           */, 
		OP_EXCLAMATION  /* !           */,
		OP_QUESTION		/* ? 		   */,
		OP_EQ           /* ==          */,
		OP_NEQ          /* !=          */, 
		OP_GE           /* >=          */,
		OP_LE           /* <=          */,
		OP_GT           /* >           */,
		OP_LT           /* <           */,
		OP_AND			/* & 		   */, 
		OP_OR			/* | 		   */,
		OP_PLUS         /* +           */,
		OP_MINUS        /* -           */,
		OP_TIMES        /* *           */,
		OP_DIV          /* /           */,
		OP_MOD          /* %           */,
		OP_POWER        /* **          */, 
		LPAREN          /* (           */,
		RPAREN          /* )           */,
		LBRACE          /* {           */, 
		RBRACE          /* }           */,
		LSQUARE			/* [           */, 
		RSQUARE			/* ]           */, 
		SEMI            /* ;           */,
		OP_COLON		/* : 		   */,
		COMMA           /* ,           */,
		DOT             /* .           */,
		EOF				/* end of file */,
	}
	
	/**
	 * Class to represent Tokens.
	 *
	 */
	public class Token {
		public final Kind kind;
		public final int pos; // position of first character of this token in the input. Counting starts at 0
								// and is incremented for every character.
		public final int length; // number of characters in this token

		public Token(Kind kind, int pos, int length) {
			super();
			this.kind = kind;
			this.pos = pos;
			this.length = length;
		}
		
		/**
		 * Calculates and returns the line on which this token resides. The first line
		 * in the source code is line 1.
		 * 
		 * @return line number of this Token in the input.
		 */
		public int line() {
			return PLPScanner.this.line(pos) + 1;
		}

		/**
		 * Returns position in line of this token.
		 * 
		 * @param line.
		 *            The line number (starting at 1) for this token, i.e. the value
		 *            returned from Token.line()
		 * @return
		 */
		public int posInLine(int line) {
			return PLPScanner.this.posInLine(pos, line - 1) + 1;
		}

		/**
		 * Returns the position in the line of this Token in the input. Characters start
		 * counting at 1. Line termination characters belong to the preceding line.
		 * 
		 * @return
		 */
		public int posInLine() {
			return PLPScanner.this.posInLine(pos) + 1;
		}
		
		public String getText() {
			return String.copyValueOf(chars, pos, length);
		}
		public String toString() {
			int line = line();
			return "[" + kind + "," +
			       String.copyValueOf(chars, pos, length) + "," +
			       pos + "," +
			       length + "," +
			       line + "," +
			       posInLine(line) + "]";
		}

		/**
		 * Since we override equals, we need to override hashCode, too.
		 * 
		 * See
		 * https://docs.oracle.com/javase/9/docs/api/java/lang/Object.html#hashCode--
		 * where it says, "If two objects are equal according to the equals(Object)
		 * method, then calling the hashCode method on each of the two objects must
		 * produce the same integer result."
		 * 
		 * This method, along with equals, was generated by eclipse
		 * 
		 */
		@Override
		public int hashCode() {
			final int prime = 31;
			int result = 1;
			result = prime * result + getOuterType().hashCode();
			result = prime * result + ((kind == null) ? 0 : kind.hashCode());
			result = prime * result + length;
			result = prime * result + pos;
			return result;
		}

		/**
		 * Override equals so that two Tokens are equal if they have the same Kind, pos,
		 * and length.
		 * 
		 * This method, along with hashcode, was generated by eclipse.
		 */
		@Override
		public boolean equals(Object obj) {
			if (this == obj)
				return true;
			if (obj == null)
				return false;
			if (getClass() != obj.getClass())
				return false;
			Token other = (Token) obj;
			if (!getOuterType().equals(other.getOuterType()))
				return false;
			if (kind != other.kind)
				return false;
			if (length != other.length)
				return false;
			if (pos != other.pos)
				return false;
			return true;
		}

		/**
		 * used in equals to get the Scanner object this Token is associated with.
		 * 
		 * @return
		 */
		private PLPScanner getOuterType() {
			return PLPScanner.this;
		}
	}
	
	/**
	 * Array of positions of beginning of lines. lineStarts[k] is the pos of the
	 * first character in line k (starting at 0).
	 * 
	 * If the input is empty, the chars array will have one element, the synthetic
	 * EOFChar token and lineStarts will have size 1 with lineStarts[0] = 0;
	 */
	int[] lineStarts;

	int[] initLineStarts() {
		ArrayList<Integer> lineStarts = new ArrayList<Integer>();
		int pos = 0;

		for (pos = 0; pos < chars.length; pos++) {
			lineStarts.add(pos);
			char ch = chars[pos];
			while (ch != EOFChar && ch != '\n' && ch != '\r') {
				pos++;
				ch = chars[pos];
			}
			if (ch == '\r' && chars[pos + 1] == '\n') {
				pos++;
			}
		}
		// convert arrayList<Integer> to int[]
		return lineStarts.stream().mapToInt(Integer::valueOf).toArray();
	}
	
	int line(int pos) {
		int line = Arrays.binarySearch(lineStarts, pos);
		if (line < 0) {
			line = -line - 2;
		}
		return line;
	}

	public int posInLine(int pos, int line) {
		return pos - lineStarts[line];
	}

	public int posInLine(int pos) {
		int line = line(pos);
		return posInLine(pos, line);
	}
	
	/**
	 * Sentinal character added to the end of the input characters.
	 */
	static final char EOFChar = 128;

	/**
	 * The list of tokens created by the scan method.
	 */
	final ArrayList<Token> tokens;

	/**
	 * An array of characters representing the input. These are the characters from
	 * the input string plus an additional EOFchar at the end.
	 */
	final char[] chars;

	/**
	 * position of the next token to be returned by a call to nextToken
	 */
	private int nextTokenPos = 0;
	
	PLPScanner(String inputString) {
		int numChars = inputString.length();
		this.chars = Arrays.copyOf(inputString.toCharArray(), numChars + 1); // input string terminated with null char
		chars[numChars] = EOFChar;
		tokens = new ArrayList<Token>();
		lineStarts = initLineStarts();
	}
	
	private enum State {START ,UNDERSCORE_START,CHAR_LIT,STRING_LIT, IDENTIFIER_START, IDENTIFIER_PART, HAS_ZERO , DIGITS , FLOATS , GOT_ZERO , GOT_EQUALS , HAS_COMMENT, COMMENT_END,HAS_MULT , HAS_LT , HAS_GT , HAS_EQ , HAS_EXCL , HAS_MOD};  //TODO:  this is incomplete
	
	public PLPScanner scan() throws LexicalException {
		int pos = 0;
		State state = State.START;
		int startPos = 0;
		
		//TODO:  this is incomplete

		while (pos < chars.length) {
			char ch = chars[pos];
			switch(state) {
				case START: {
					startPos = pos;
					switch (ch) {
					case ' ':
					case '\n':
					case '\r':
					case '\t':
					case '\f': {
						pos++;
					}
					break;
						case EOFChar: {
							if(pos== chars.length-1){
								tokens.add(new Token(Kind.EOF, startPos, 0));
								pos++; // next iteration will terminate loop
							}
							else{
								error(pos, line(pos), posInLine(pos), "EOF encountered before the entire input");
							}
						}
						break;
						case ';': {
							tokens.add(new Token(Kind.SEMI, startPos, pos - startPos + 1));
							pos++;
						}
						break;
						
						case '(': {
							tokens.add(new Token(Kind.LPAREN, startPos, pos - startPos + 1));
							pos++;
						}
						break;
						
						case ')': {
							tokens.add(new Token(Kind.RPAREN, startPos, pos - startPos + 1));
							pos++;
						}
						break;

						case '[': {
							tokens.add(new Token(Kind.LSQUARE, startPos, pos - startPos + 1));
							pos++;
						}
						break;
						

						case ']': {
							tokens.add(new Token(Kind.RSQUARE, startPos, pos - startPos + 1));
							pos++;
						}
						break;
						

						case ',': {
							tokens.add(new Token(Kind.COMMA, startPos, pos - startPos + 1));
							pos++;
						}
						break;
						

						case '{': {
							tokens.add(new Token(Kind.LBRACE, startPos, pos - startPos + 1));
							pos++;
						}
						break;
						

						case '}': {
							tokens.add(new Token(Kind.RBRACE, startPos, pos - startPos + 1));
							pos++;
						}
						break;
						
						case '?': {
							tokens.add(new Token(Kind.OP_QUESTION, startPos, pos - startPos + 1));
							pos++;
						}
						break;
						
						case ':': {
							tokens.add(new Token(Kind.OP_COLON, startPos, pos - startPos + 1));
							pos++;
						}
						break;
						
						case '|': {
							tokens.add(new Token(Kind.OP_OR, startPos, pos - startPos + 1));
							pos++;
						}
						break;
						
						case '&': {
							tokens.add(new Token(Kind.OP_AND, startPos, pos - startPos + 1));
							pos++;
						}
						break;
						

						case '<': {
							state = State.HAS_LT;							
							pos++;
						}
						break;
						

						case '>': {
							state = State.HAS_GT;							
							pos++;
						}
						break;
						case '=': {
							state = State.HAS_EQ;							
							pos++;
						}
						break;
						
						case '-': {
							tokens.add(new Token(Kind.OP_MINUS, startPos, pos - startPos + 1));
							pos++;
						}
						break;
						
						case '+': {
							tokens.add(new Token(Kind.OP_PLUS, startPos, pos - startPos + 1));
							pos++;
						}
						break;
						
						case '*': {
							state = State.HAS_MULT;							
							pos++;
						}
						break;
						
						case '/': {
							tokens.add(new Token(Kind.OP_DIV, startPos, pos - startPos + 1));
							pos++;
						}
						break;
						
						case '%': {
							state = State.HAS_MOD;							
							pos++;
						}
						break;
						
						case '!': {
							state = State.HAS_EXCL;							
							pos++;
							
						}
						break;
						
						case '_': {
							state=State.UNDERSCORE_START;
							pos++;
							
						}
						break;
						
						case '0': {
							state=State.HAS_ZERO;
							pos++;				
							
						}
						break;
						
						case '\'': {							
							state=State.CHAR_LIT;
							pos++;
							
							
						}
						break;
						case '\"': {
							
							state=State.STRING_LIT;
							pos++;
							
							
						}
						break;
						default: {
						
						if(Character.isDigit(ch) && (ch!='0')){
							state=State.DIGITS;
							pos++;
						}
						else if(Character.isLetter(ch)){
							state=State.IDENTIFIER_PART;
							pos++;
						}						
						else {
							error(pos, line(pos), posInLine(pos), "illegal char");
						}
							
						}
					}
				}
				break;
				
				case HAS_LT: {
					if(ch=='=') {
						tokens.add(new Token(Kind.OP_LE, startPos, pos - startPos + 1));
						pos++;
						state = State.START;
					}
					else {
						tokens.add(new Token(Kind.OP_LT, startPos, pos - startPos));							
						state = State.START;						
					}								
				}
				break;
				
				case HAS_GT: {
					if(ch=='=') {
						tokens.add(new Token(Kind.OP_GE, startPos, pos - startPos + 1));
						pos++;
						state = State.START;
					}
					else {
						tokens.add(new Token(Kind.OP_GT, startPos, pos - startPos));						
						state = State.START;						
					}						
				}
				break;
				
				case HAS_EQ: {
					if(ch=='=') {
						tokens.add(new Token(Kind.OP_EQ, startPos, pos - startPos + 1));
						pos++;
						state = State.START;
					}
					else {
						tokens.add(new Token(Kind.OP_ASSIGN, startPos, pos - startPos));							
						state = State.START;						
					}
							
				}
				break;
				
				case HAS_EXCL: {
					if(ch=='=') {
						tokens.add(new Token(Kind.OP_NEQ, startPos, pos - startPos + 1));
						pos++;
						state = State.START;
					}
					else {
						tokens.add(new Token(Kind.OP_EXCLAMATION, startPos, pos - startPos));							
						state = State.START;						
					}
					
				}
				break;
				
				case HAS_MULT: {
					if(ch=='*') {
						tokens.add(new Token(Kind.OP_POWER, startPos, pos - startPos + 1));
						pos++;
						state = State.START;
					}
					else {
						tokens.add(new Token(Kind.OP_TIMES, startPos, pos - startPos));							
						state = State.START;						
					}
						
				}
				break;
				
				case HAS_MOD: {
					if(ch=='{') {
						state = State.HAS_COMMENT;
						pos++;
					}
					else {
						tokens.add(new Token(Kind.OP_MOD, startPos, pos - startPos));							
						state = State.START;						
					}
							
				}
				
				break;
				
				
				
				
				case HAS_COMMENT: {
					if(ch=='%'){
						
						state = State.COMMENT_END;
						pos++;
					}
					else if(ch==EOFChar){
						error(pos, line(pos), posInLine(pos), "Comments not properly closed");
					}
					else{
						pos++;
					}		
				}
				break;
				
				case COMMENT_END: {					
					if(ch=='}'){
						
						state = State.START;
						pos++;
					}
					else if(ch=='{') {
						error(pos, line(pos), posInLine(pos), "Illegeal nesting of comments");
						
					}
					else{
						state = State.HAS_COMMENT;						
						
					}
				}
				break;
				
				case UNDERSCORE_START: {
					switch(ch){
						case '_': {							
							pos++;							
						}
						break;
						default: {
							if(Character.isLetter(ch)){
								state=State.IDENTIFIER_PART;
								pos++;
							}
							else {
								error(pos, line(pos), posInLine(pos), "illegal Identifier");
							
							}
							
						}
										
					}			
				}
				break;
				
				case IDENTIFIER_PART: {
					if(Character.isLetter(ch) || Character.isDigit(ch)|| ch =='_' ){						
						pos++;
					}
					else {
						int i = startPos;
						String s="";
						
						while(i<pos){
							s=s+(chars[i]);
							i++;
						}
						
						switch (s){
							
							case "print": {
								tokens.add(new Token(Kind.KW_print, startPos, pos - startPos));
								state = State.START;
							}
							break;

							case  "int" : {
								tokens.add(new Token(Kind.KW_int, startPos, pos - startPos));
								state = State.START;
							}
							break;
							
							case  "float" : {
								tokens.add(new Token(Kind.KW_float, startPos, pos - startPos));
								state = State.START;
							}
							break;
							
							case "boolean" : {
								tokens.add(new Token(Kind.KW_boolean, startPos, pos - startPos));
								state = State.START;
							}
							break;
							
							case "char": {
								tokens.add(new Token(Kind.KW_char, startPos, pos - startPos));
								state = State.START;
							}
							break;
							
							case "string" : {
								tokens.add(new Token(Kind.KW_string, startPos, pos - startPos));
								state = State.START;
							}
							break;							
						
							
							case "if": {
								tokens.add(new Token(Kind.KW_if, startPos, pos - startPos));
								state = State.START;
							}
							break;
							
							case "sleep": {
								tokens.add(new Token(Kind.KW_sleep, startPos, pos - startPos));
								state = State.START;
							}
							break;
							
							case "while": {
								tokens.add(new Token(Kind.KW_while, startPos, pos - startPos));
								state = State.START;
							}
							break;
							
							case "sin": {
								tokens.add(new Token(Kind.KW_sin, startPos, pos - startPos));
								state = State.START;
							}
							break;
							
							case "cos": {
								tokens.add(new Token(Kind.KW_cos, startPos, pos - startPos));
								state = State.START;
							}
							break;
							
							case "atan": {
								tokens.add(new Token(Kind.KW_atan, startPos, pos - startPos));
								state = State.START;
							}
							break;
							
							case "abs": {
								tokens.add(new Token(Kind.KW_abs, startPos, pos - startPos));
								state = State.START;
							}
							break;
							
							case "log": {
								tokens.add(new Token(Kind.KW_log, startPos, pos - startPos));
								state = State.START;
							}
							break;
														
							case "true": {
								tokens.add(new Token(Kind.BOOLEAN_LITERAL, startPos, pos - startPos));
								state = State.START;
							}
							break;
							
							case "false": {
								tokens.add(new Token(Kind.BOOLEAN_LITERAL, startPos, pos - startPos));
								state = State.START;
							}
							break;
							default: {
								tokens.add(new Token(Kind.IDENTIFIER, startPos, pos - startPos));
								state = State.START;
							}
						
					}
					
				}
					
				}
				break;
				
				case HAS_ZERO:{
					if(ch=='.'){
						state = State.FLOATS;
						pos++;
					}
					else {
						tokens.add(new Token(Kind.INTEGER_LITERAL, startPos, pos - startPos));
						state = State.START;
					}					
					
				}
				break;
				
				case DIGITS: {
					if(Character.isDigit(ch)){						
						pos++;
					}
					else {
						if(ch=='.') {
							state = State.FLOATS;
							pos++;
						}
						else {
							int i = startPos;
							String s="";
							
							while(i<pos){
								s=s+(chars[i]);
								i++;
							}
							try{
								int size_check=Integer.parseInt(s);
								if(size_check > Integer.MAX_VALUE){
									throw new Exception("Integer out of range");
								}
								else {
									tokens.add(new Token(Kind.INTEGER_LITERAL, startPos, pos - startPos));
									state = State.START;
								}
								
							}
							catch(Exception ex){
								error(pos, line(pos), posInLine(pos), "Integer out of Range");
							}
							
						}
						
					}
				}
				break;
				
				case FLOATS:{
					if(Character.isDigit(ch)){						
						pos++;
					}
					else {
						int temp = pos -1;
						if(chars[temp]=='.') {
							error(pos, line(pos), posInLine(pos), "illegal float");
						}
						else {
							int i = startPos;
							String s="";
							
							while(i<pos){
								s=s+(chars[i]);
								i++;
							}
							
							
							try{							
								float size_check = Float.parseFloat(s);
								if(size_check > Float.MAX_VALUE){
									throw new Exception("Float out of range");
								}
								else {
									tokens.add(new Token(Kind.FLOAT_LITERAL, startPos, pos - startPos));
									state = State.START;
								}
								
								
							}
							catch(Exception ex){
								error(pos, line(pos), posInLine(pos), "Float out of Range");
							}
							
							
						}
						
					}					
					
				}
				break;
				case CHAR_LIT:{
					int temp = ch;
					if(ch=='\'') {
						tokens.add(new Token(Kind.CHAR_LITERAL,startPos, pos - startPos+1));
						state = State.START;
						pos++;
					}
					
					else if(0<=temp && temp<128){						
						pos++;
						if(chars[pos]=='\'') {
							tokens.add(new Token(Kind.CHAR_LITERAL,startPos, pos - startPos+1));
							state = State.START;
							pos++;
						}
						else {
							error(pos, line(pos), posInLine(pos), "illegal char literal");
						}
					}
					else {
						error(pos, line(pos), posInLine(pos), "illegal char literal");
						
					}					
					
				}
				break;
				case STRING_LIT:{
					if(ch == '\"'){						
						tokens.add(new Token(Kind.STRING_LITERAL,startPos, pos - startPos+1));
						state = State.START;
						pos++;
					}					
					else {
						int temp = ch;						
						if(0<=temp && temp<128){						
							pos++;
						}
						else {
							error(pos, line(pos), posInLine(pos), "illegal String literal");
						}
						
					}					
					
				}
				break;
				
				default: {
					error(pos, 0, 0, "undefined state");
				}
			}// switch state
		} // while
		
		return this;
	}
	
	private void error(int pos, int line, int posInLine, String message) throws LexicalException {
		String m = (line + 1) + ":" + (posInLine + 1) + " " + message;
		throw new LexicalException(m, pos);
	}

	/**
	 * Returns true if the internal iterator has more Tokens
	 * 
	 * @return
	 */
	public boolean hasTokens() {
		return nextTokenPos < tokens.size();
	}

	/**
	 * Returns the next Token and updates the internal iterator so that the next
	 * call to nextToken will return the next token in the list.
	 * 
	 * It is the callers responsibility to ensure that there is another Token.
	 * 
	 * Precondition: hasTokens()
	 * 
	 * @return
	 */
	public Token nextToken() {
		return tokens.get(nextTokenPos++);
	}

	/**
	 * Returns the next Token, but does not update the internal iterator. This means
	 * that the next call to nextToken or peek will return the same Token as
	 * returned by this methods.
	 * 
	 * It is the callers responsibility to ensure that there is another Token.
	 * 
	 * Precondition: hasTokens()
	 * 
	 * @return next Token.
	 */
	public Token peek() {
		return tokens.get(nextTokenPos);
	}

	/**
	 * Resets the internal iterator so that the next call to peek or nextToken will
	 * return the first Token.
	 */
	public void reset() {
		nextTokenPos = 0;
	}

	/**
	 * Returns a String representation of the list of Tokens and line starts
	 */
	public String toString() {
		StringBuffer sb = new StringBuffer();
		sb.append("Tokens:\n");
		for (int i = 0; i < tokens.size(); i++) {
			sb.append(tokens.get(i)).append('\n');
		}
		sb.append("Line starts:\n");
		for (int i = 0; i < lineStarts.length; i++) {
			sb.append(i).append(' ').append(lineStarts[i]).append('\n');
		}
		return sb.toString();
	}


}

